#!/bin/bash
echo "==========Configuring BTSMED=========="
/usr/bin/expect <<-EOF
spawn sudo -u Nemuadmin /opt/imp/`rpm -qa | grep nokia | cut -d "-" -f 3`/cli/bin/imp-cli-control.sh start
expect "btsmed>"
send "config set --dn /BTSMED-1\r"
expect "*dnsIPAddress:"
send "10.91.81.26\r"
expect "*northboundGateway:"
send "10.91.80.1\r"
expect "*northboundIpAddress:"
send "10.91.82.200\r"
expect "*northboundIpPrefixLength:"
send "20\r"
expect "*ntpIPAddress1:"
send "10.91.81.26\r"
expect "*ntpIPAddress2:"
send "10.91.81.26\r"
expect "*ntpIPAddress3:"
send "10.91.81.26\r"
expect "*southboundGateway:"
send "10.92.16.1\r"
expect "*southboundIpAddress:"
send "10.92.19.149\r"
expect "*southboundIpPrefixLength:"
send "20\r"
expect "*timeZone:"
send "\r"
expect "*tlsModeNorthbound:"
send "Off\r"
expect "*tlsModeSouthbound:"
send "\r"
expect "btsmed>"
send "config commit\r"
expect "*(y/n)"
send "y\r"
expect eof
EOF