##################################################
# file: NasdaWSPersistency_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/bin/wsdl2py --complexType NasdaWSPersistencyService.wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from NasdaWSPersistency_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
getMOLitesRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMOLitesRequest").pyclass

getMOLitesResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMOLitesResponse").pyclass

getManagedObjectsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMOsRequest").pyclass

getManagedObjectsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMOsResponse").pyclass

getRelatedMOLitesRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetRelatedMOLitesRequest").pyclass

getRelatedMOLitesResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetRelatedMOLitesResponse").pyclass

createManagedObjectsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "CreateMOsRequest").pyclass

createManagedObjectsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "CreateMOsResponse").pyclass

updateManagedObjectsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "UpdateMOsRequest").pyclass

updateManagedObjectsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "UpdateMOsResponse").pyclass

deleteManagedObjectsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "DeleteMOsRequest").pyclass

deleteManagedObjectsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "DeleteMOsResponse").pyclass

createRelationshipsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "CreateRelationshipsRequest").pyclass

createRelationshipsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "CreateRelationshipsResponse").pyclass

deleteRelationshipsRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "RemoveRelationshipsRequest").pyclass

deleteRelationshipsResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "RemoveRelationshipsResponse").pyclass

queryMOLitesRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "QueryMOLitesRequest").pyclass

queryMOLitesResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "QueryMOLitesResponse").pyclass

getMetadataRequest = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMetadataRequest").pyclass

getMetadataResponse = GED("http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/operations", "GetMetadataResponse").pyclass


# Service Skeletons
class NasdaWSPersistencyService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/netact/oss/nasda/ws-api/NasdaWSPersistencyServiceSOAP', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_getMOLites(self, ps, **kw):
        request = ps.Parse(getMOLitesRequest.typecode)
        return request,getMOLitesResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/getMOLites'] = 'soap_getMOLites'
    root[(getMOLitesRequest.typecode.nspname,getMOLitesRequest.typecode.pname)] = 'soap_getMOLites'

    def soap_getManagedObjects(self, ps, **kw):
        request = ps.Parse(getManagedObjectsRequest.typecode)
        return request,getManagedObjectsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/getManagedObjects'] = 'soap_getManagedObjects'
    root[(getManagedObjectsRequest.typecode.nspname,getManagedObjectsRequest.typecode.pname)] = 'soap_getManagedObjects'

    def soap_getRelatedMOLites(self, ps, **kw):
        request = ps.Parse(getRelatedMOLitesRequest.typecode)
        return request,getRelatedMOLitesResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/getRelatedMOLites'] = 'soap_getRelatedMOLites'
    root[(getRelatedMOLitesRequest.typecode.nspname,getRelatedMOLitesRequest.typecode.pname)] = 'soap_getRelatedMOLites'

    def soap_createManagedObjects(self, ps, **kw):
        request = ps.Parse(createManagedObjectsRequest.typecode)
        return request,createManagedObjectsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/createManagedObjects'] = 'soap_createManagedObjects'
    root[(createManagedObjectsRequest.typecode.nspname,createManagedObjectsRequest.typecode.pname)] = 'soap_createManagedObjects'

    def soap_updateManagedObjects(self, ps, **kw):
        request = ps.Parse(updateManagedObjectsRequest.typecode)
        return request,updateManagedObjectsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/updateManagedObjects'] = 'soap_updateManagedObjects'
    root[(updateManagedObjectsRequest.typecode.nspname,updateManagedObjectsRequest.typecode.pname)] = 'soap_updateManagedObjects'

    def soap_deleteManagedObjects(self, ps, **kw):
        request = ps.Parse(deleteManagedObjectsRequest.typecode)
        return request,deleteManagedObjectsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/deleteManagedObjects'] = 'soap_deleteManagedObjects'
    root[(deleteManagedObjectsRequest.typecode.nspname,deleteManagedObjectsRequest.typecode.pname)] = 'soap_deleteManagedObjects'

    def soap_createRelationships(self, ps, **kw):
        request = ps.Parse(createRelationshipsRequest.typecode)
        return request,createRelationshipsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/relationshipservice/createRelationships'] = 'soap_createRelationships'
    root[(createRelationshipsRequest.typecode.nspname,createRelationshipsRequest.typecode.pname)] = 'soap_createRelationships'

    def soap_deleteRelationships(self, ps, **kw):
        request = ps.Parse(deleteRelationshipsRequest.typecode)
        return request,deleteRelationshipsResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/relationshipservice/removeRelationships'] = 'soap_deleteRelationships'
    root[(deleteRelationshipsRequest.typecode.nspname,deleteRelationshipsRequest.typecode.pname)] = 'soap_deleteRelationships'

    def soap_queryMOLites(self, ps, **kw):
        request = ps.Parse(queryMOLitesRequest.typecode)
        return request,queryMOLitesResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/queryMOLites'] = 'soap_queryMOLites'
    root[(queryMOLitesRequest.typecode.nspname,queryMOLitesRequest.typecode.pname)] = 'soap_queryMOLites'

    def soap_getMetadata(self, ps, **kw):
        request = ps.Parse(getMetadataRequest.typecode)
        return request,getMetadataResponse()

    soapAction['http://www.nsn.com/schemas/public/oss/nasda/ws-api/persistency/NasdaWSPersistency/getMetadata'] = 'soap_getMetadata'
    root[(getMetadataRequest.typecode.nspname,getMetadataRequest.typecode.pname)] = 'soap_getMetadata'

