apiVersion: v1
kind: Secret

metadata:
  name: "tls-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.certificate }}
  tls.key: {{ .Values.private_key }}
type: kubernetes.io/tls
