apiVersion: v1
kind: Secret

metadata:
  name: "tls-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.certificate }}
  tls.key: {{ .Values.private_key }}
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: "registrykey-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.registryKey }}
type: kubernetes.io/dockerconfigjson
