apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-rest"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apprest.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
  - name: tvnf-rest
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "apprest.fullname" . }}
