CASE_LIST = [
'Integrate NE through NEIW',
'Verify PM data coming',
'Alarm upload by fmCLI',
'Launch Adaptation Manager',
'Launch Administration of Measurements',
'Launch Alarm Reports Dashboard',
'Launch CM Analyzer',
'Launch CM Editor',
'Launch CM Operations Manager',
'Launch CM Reference',
'Launch CM Rule Editor',
'Launch CM Policy Manager',
'Launch Certification Authority',
'Launch Dynamic Adaptation',
'Launch Flexible CM Search',
'Launch Integration Express',
'Launch Intelligent Feature Activation',
'Launch License Manager',
'Launch MSC Server Pool Monitor',
'Launch Network Element Access Control',
'Launch NE Integration Wizard',
'Launch Object Information Browser',
'Launch Operating Documentation',
'Launch Performance Manager',
'Launch Plain SNMP FM Mediator',
'Launch Plain SNMP PM Mediator',
'Launch Site Configuration Tool',
'Launch Software Asset Monitoring',
'Launch Software Manager',
'Launch System Monitoring',
'Launch TraceViewer',
'Launch User Management',
'Launch Working Set Manager',
'Adaptation Configuration',
'Administration Of Aggregates',
'CM Command Line: SAT',
'CM Deleting NE data from Configurator',
'CM Export Import: Export Actual Configuration to CSV - CMOP',
'CM Export Import: Export Actual Configuration to XML - CMOP',
'CM Export Import: Export Actual to XLSX - CMED',
'CM Export Import: Export Actual to CSV - CMED',
'CM Export Import: Export Plan to XML - CMOP',
'CM Export Import: Export Plan to CSV, Import, Generate Delta Plan',
'CM Export Import: Export Reference Configuration to CSV - CMOP',
'CM Export Import: Export Reference Configuration to XML - CMOP',
'CM Export Import: Import Actual Configuration from CSV - CMOP',
'CM Export Import: Import Actual Configuration from XML - CMOP',
'CM Export Import: Import Plan from XLSX - CMED',
'CM Export Import: Import Plan from XML - CMOP',
'CM History: Using operations based on CM history data',
'CM Intelligent Feature Activation',
'CM Upload: Execute Upload',
'CM Upload: Execute HW Upload',
'CM Upload: using non-sysop user which is not existing in UM tool',
'CM Racclimx webservice-based operations as sysop user',
'CM Racclimx webservice-based operations as non-sysop user',
'CM Reference: Delta Analyzing And Alignment',
'CM Plan: Creation: general',
'CM Plan: Creating Mass Modification Plan',
'CM S2N: Modify MO',
'CM Seach and Modify - Add to WS',
'Storing Period Configuration',
'SWM: Status Upload',
'SWM Set: Export',
'Verification of Partitioning and Indexing Logs',
'WS Export Working Set from WS Manager',
]
